# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/lucabecchetti/swiftmultiselect.git'

target 'SwiftMultiSelectTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftMultiSelectTest
  pod 'SwiftMultiSelect', :path => "../"
end
